services:
  minecraft-server:
    container_name: minecraft
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      EULA: true
      MEMORY: 8G 
      #TYPE: CURSEFORGE
      #CF_SERVER_MOD: https://mediafilez.forgecdn.net/files/4745/395/SteamPunk_Server_Pack_v9.zip
    volumes:
      - ./data:/data

