---
services:

  unifi-db:
    image: mongo:7.0.11
    container_name: unifi-db
    restart: unless-stopped
    volumes:
      - db:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - unifi_network

networks:
  unifi_network:

volumes:
  db:
